### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by afonsopacifer** [busca-dev/busca-starter-kit#1]
### Próximos passos:
- [ ] Adicionar tarefa para otimizar as imagens automaticamente.
- [ ] Organizar dependências de Front-End no Bower.
- [x] Automatizar Deploy.
- [ ] Criar um generator de Yeoman.
- [ ] Criar snippets .
- [ ] Criar um code style guide.
- [ ] Descrever estrutura do projeto no readme.md.
- [ ] Automatizar criação de meta tags - SEO
- [ ] Automatizar criação de meta tags - Graph
- [ ] Automatizar criação de meta tags - Twitter Cards
- [x] Adicionar um guia de contribuição.
- [x] Adicionar ao readme informações sobre as regras de versionamento.
- [x] Definir e adicionar licença.

@janasouza, @k2cl fiquem a vontade para adicionar mais melhorias.
